### ISSUE TITLE
People are committing temporary files (files ending with a ~) - We should add a .gitignore to prevent git from committing them

### ISSUE THREAD

**Issue by ss23** [ProzacJellybeans/SStheme#1]

**Comment by emmahuangokeefe** [comment]
Fixed

On 15 January 2015 at 15:22, ☃ Stephen Shkardoon ☃ <notifications@github.com

**Comment by ss23** [comment]
You missed .css~!
If you make it just *~, that should include all of them (any files ending in ~)

**Comment by elliot-sawyer** [comment]
*~ didn't work  :(

I've made a pull request for the CSS temp files and showed @ProzacJellybeans how to inspect and merge it
